api/build.gradle.kts
api/src/main/kotlin/com/gmtkgamejam/Application.kt
api/src/main/kotlin/com/gmtkgamejam/plugins/Auth.kt
api/src/main/kotlin/com/gmtkgamejam/plugins/Routing.kt
api/src/main/resources/application.conf

Pull request to include the authentication setup

Auth implementation

---

api/src/main/kotlin/com/gmtkgamejam/models/Skills.kt
api/src/main/kotlin/com/gmtkgamejam/models/Team.kt
api/src/main/kotlin/com/gmtkgamejam/plugins/TeamRoutes.kt

Speculative PR draft to remove use of bitwise logic; the scale and performance of the app means we don't really get a whole lot of value from it, but it complicated queries in a way that will be _very_ difficult to port to Mongo.

Create helper function to start deprecation of skillsetMask

---

api/src/main/kotlin/com/gmtkgamejam/plugins/Routing.kt
ui/src/pages/Login/AuthorizedCallback.tsx

Tidy up pruning to stale PR in order to unblock userinfo progress

Userinfo endpoint stability amends

---

.postman/GMTK - API.postman_collection.json
api/src/main/kotlin/com/gmtkgamejam/models/AuthTokenSet.kt
api/src/main/kotlin/com/gmtkgamejam/models/DiscordGuildInfo.kt
api/src/main/kotlin/com/gmtkgamejam/models/DiscordUserInfo.kt
api/src/main/kotlin/com/gmtkgamejam/plugins/Auth.kt
api/src/main/kotlin/com/gmtkgamejam/plugins/Routing.kt
api/src/main/kotlin/com/gmtkgamejam/services/AuthService.kt
openapi.json
ui/src/components/PageUserInfo.tsx
ui/src/pages/Login/AuthorizedCallback.tsx
ui/src/utils/ApiRequest.ts
ui/src/utils/TeamActions.ts
ui/src/utils/UserInfo.ts

Allow front-end to pull basic User data from Discord

---

api/src/main/kotlin/com/gmtkgamejam/plugins/PostRoutes.kt
db/seed/data.json
ui/src/utils/LanguageData.ts

Adding `?.filter { it != "" }` is a quick tidy-up to remove querying for empty strings

Update language list to be more meaningful

---

ui/src/pages/Home/Home.tsx

This is only intended as a short-term UI fix to get filtering on par with API

Use new skill filtering option and remove skillsetMask from UI

---

api/src/main/kotlin/com/gmtkgamejam/plugins/Auth.kt
ui/src/AppRoutes.tsx
ui/src/Context.tsx
ui/src/pages/AuthCallback/AuthCallback.tsx
ui/src/pages/TestAuthenticatedPage/TestAuthenticatedPage.tsx
ui/src/queries/posts.ts
ui/src/queries/userInfo.ts
ui/src/test-utils/createTestContext.ts
ui/src/test-utils/renderWithContext.tsx
ui/src/utils/AuthContext.tsx
ui/src/utils/apiRequest.ts
ui/src/utils/useEnsureLoggedIn.ts

Just a lil page to try to authenticate with Discord and the API, and then fetch userInfo.

Proof of concept frontend auth architecture

---

api/src/main/kotlin/com/gmtkgamejam/plugins/Auth.kt
api/src/main/kotlin/com/gmtkgamejam/plugins/Routing.kt
api/src/main/kotlin/com/gmtkgamejam/services/AuthService.kt

Ensure user's auth session is still valid per request

---

api/src/main/kotlin/com/gmtkgamejam/models/PostItem.kt
api/src/main/kotlin/com/gmtkgamejam/models/PostItemCreateDto.kt
api/src/main/kotlin/com/gmtkgamejam/models/PostItemUpdateDto.kt
api/src/main/kotlin/com/gmtkgamejam/plugins/PostRoutes.kt
db/seed/data.json

Developers will need to run `docker compose up --build db-seed` to regenerate the DB records.

Add a title field to PostItem records

---

.env.example
api/src/main/kotlin/com/gmtkgamejam/models/PostItemUpdateDto.kt
api/src/main/kotlin/com/gmtkgamejam/plugins/PostRoutes.kt
ui/src/AppRoutes.tsx
ui/src/components/Button.tsx
ui/src/components/PostPreview.tsx
ui/src/main.tsx
ui/src/model/post.ts
ui/src/pages/MyPost/MyPost.tsx
ui/src/pages/MyPost/index.ts
ui/src/queries/my-post.ts
ui/src/queries/posts.ts
ui/src/test-utils/fixtures/posts.ts
ui/src/utils/AuthContext.tsx
ui/src/utils/apiRequest.ts
ui/tailwind.config.js

Only the one field to start with, but it saves at least!

My Post page

---

ui/src/model/availability.ts
ui/src/model/post.ts
ui/src/pages/AvailabilitySelector.tsx
ui/src/pages/Home/Home.tsx
ui/src/queries/my-post.ts
ui/src/queries/posts.ts

Inclusive Availability option filtering

Add availability options filter

---

ui/src/components/PostModal.tsx
ui/src/components/PostPreview.tsx
ui/src/components/SkillList.tsx
ui/src/pages/Admin/Admin.tsx
ui/src/pages/AvailabilitySelector.tsx
ui/src/pages/Home/Home.tsx
ui/src/pages/Home/components/ViewOptions.tsx

UI tweaks for wvpd

---

ui/src/pages/Home/components/Onboarding.tsx

Amend copy on login prompt

---

ui/src/pages/PageHeader/PageHeader.tsx

Reduce emphasis on logout prompt

---

ui/src/pages/MyPost/MyPost.tsx
ui/src/pages/PageHeader/PageHeader.tsx

Amends to My Post page

---

ui/src/components/StyledSelector/StyledSelector.css
ui/src/pages/Home/Home.tsx
ui/src/pages/MyPost/MyPost.tsx

Standardise form field bg colours

---

ui/src/index.css
ui/src/pages/Home/Home.tsx
ui/src/pages/Home/components/ViewOptions.tsx

Improve visual of availability selector and show skill names

---

ui/src/pages/Home/Home.tsx
ui/src/pages/MyPost/MyPost.tsx
ui/src/pages/PageHeader/PageHeader.tsx

Add page labels (to be merged in order)

---

ui/src/pages/Home/Home.tsx
ui/src/pages/MyPost/MyPost.tsx

Add home/post page labels

---

ui/src/pages/AvailabilitySelector.tsx

Improve accessibility for Availability buttons

---

api/src/main/kotlin/com/gmtkgamejam/ApplicationResponseExtensions.kt
api/src/main/kotlin/com/gmtkgamejam/routing/AdminRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/routing/DiscordBotRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/routing/FavouritesRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/routing/PostRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/routing/UserInfoRoutes.kt

Allow the UI to more gracefully handle failed requests

---

ui/src/pages/FAQ/FAQ.tsx
ui/src/pages/Home/components/Onboarding.tsx

Improve FAQ page

---

ui/package-lock.json
ui/package.json
ui/src/main.tsx
ui/src/utils/apiRequest.ts

Something super simple to have API request failures display to users. We need to improve styling and message content after #177 is also merged

Add simple UI feedback for failed requests

---

api/src/main/kotlin/com/gmtkgamejam/bot/DiscordBot.kt

Don't merge until name has been finalised

Point discord bot pings to the correct channel

---

api/build.gradle.kts
api/src/main/kotlin/com/gmtkgamejam/bot/DiscordBot.kt
api/src/main/kotlin/com/gmtkgamejam/routing/DiscordBotRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/routing/UserInfoRoutes.kt
api/src/main/resources/logback.xml

Improve logging for prod

---

ui/src/pages/Home/Home.tsx
ui/src/pages/Home/components/LoadingSpinner.tsx

Pretty crappy solution, but it seems to work for now - what do you think?

[Speculative] Stop page bouncing on query update

---

ui/src/pages/LanguageSelector.tsx
ui/src/pages/SkillSelector.tsx
ui/src/pages/ToolSelector.tsx

Don't close multi-selects after choosing one option

---

ui/src/model/sortBy.ts
ui/src/model/sortOrder.ts
ui/src/pages/Home/Home.tsx
ui/src/pages/Home/components/SortBySelector.tsx
ui/src/pages/Home/components/SortOrderSelector.tsx
ui/src/pages/Home/components/SortingOptions.tsx

Search result sorting

---

api/src/main/kotlin/com/gmtkgamejam/routing/PostRoutes.kt
ui/src/pages/Home/Home.tsx
ui/src/pages/Home/components/SearchModeSelector.tsx
ui/src/queries/posts.ts

Note the changed number of results in each screenshot
Mobile view

Allow users to switch between 'A and B' and 'A or B' skill queries

---

api/src/main/kotlin/com/gmtkgamejam/routing/DiscordBotRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/routing/FavouritesRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/routing/PostRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/services/AuthService.kt

Just refactoring out some duplicate LoC

Some idle tidy up

---

api/src/main/kotlin/com/gmtkgamejam/bot/DiscordBot.kt
api/src/main/resources/application.conf
ui/src/components/PostModal.tsx
ui/src/components/PostPreview/PostPreview.tsx
ui/src/pages/Home/Home.tsx
ui/src/pages/Logout/Logout.tsx
ui/src/pages/MyPost/MyPost.tsx
ui/src/queries/bot.ts
ui/src/queries/my-post.ts
ui/src/queries/posts.ts

- Better experience for setting channel name
- Cache successes to avoid rate limit hits
- Stop pings coming from un-contactable strangers

Improve discord integration

---

ui/src/components/PostViewWrapper.tsx

Remove blank page on page load

---

.env.example
ui/src/App.tsx
ui/src/AppRoutes.tsx
ui/src/env.d.ts
ui/src/main.tsx
ui/src/pages/AfterJam/AfterJam.tsx
ui/src/pages/BeforeJam/BeforeJam.tsx
ui/src/pages/PageHeader/PageHeader.tsx
ui/src/utils/jamState.ts

Automatically turn off Team Finder when jam has reached preset finish time

---

api/src/main/kotlin/com/gmtkgamejam/models/auth/DiscordUserInfo.kt
api/src/main/kotlin/com/gmtkgamejam/models/auth/UserInfo.kt

Nothing broke locally, but I have no idea that I even tested it properly

Allow deserialising a null avatar

---

api/build.gradle.kts
api/gradle.properties
api/src/main/kotlin/com/gmtkgamejam/routing/PostRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/routing/UserInfoRoutes.kt

No functionality changed, but I have moved a couple of things around to make reading the code easier.
There'll be a bigger update one day if/when I can be bothered.

Update dep versions and perform some trivial tidy up

---

api/src/main/kotlin/com/gmtkgamejam/koin/DatabaseModule.kt
api/src/main/kotlin/com/gmtkgamejam/models/analytivs/AnalyticsCommonEvents.kt
api/src/main/kotlin/com/gmtkgamejam/models/analytivs/AnalyticsViewEvent.kt
api/src/main/kotlin/com/gmtkgamejam/models/posts/PostItem.kt
api/src/main/kotlin/com/gmtkgamejam/repositories/AnalyticsRepository.kt
api/src/main/kotlin/com/gmtkgamejam/repositories/PostRepository.kt
api/src/main/kotlin/com/gmtkgamejam/routing/PostRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/routing/UserInfoRoutes.kt
api/src/main/kotlin/com/gmtkgamejam/services/AnalyticsService.kt
api/src/main/kotlin/com/gmtkgamejam/services/PostService.kt

Add basic internal app analytics
